import { createClient } from '@supabase/supabase-js';
import { Database } from './types';
import { projectId, publicAnonKey } from './info';

// Use credentials from info.tsx (autogenerated by Figma Make)
const supabaseUrl = `https://${projectId}.supabase.co`;
const supabaseAnonKey = publicAnonKey;

// Check if Supabase is properly configured
export const isSupabaseConfigured = (): boolean => {
  return !!(projectId && publicAnonKey && projectId !== 'placeholder');
};

// Check if we're running in browser (client-side)
const isBrowser = typeof window !== 'undefined';

// Storage key for Supabase auth token
const AUTH_STORAGE_KEY = `sb-${projectId}-auth-token`;

// Validate storage key format (ensure projectId is valid)
if (isSupabaseConfigured() && projectId.includes('${')) {
  console.error('❌ Invalid projectId - contains template literal:', projectId);
  console.error('Please check /utils/supabase/info.tsx');
}

// Check if we're in development mode (safe check)
const isDevelopment = typeof import.meta !== 'undefined' &&
                      import.meta.env &&
                      import.meta.env.DEV === true;

// Log configuration status
if (isSupabaseConfigured()) {
  console.log('✅ Supabase bağlantısı başarılı');
  console.log(`📡 Supabase URL: ${supabaseUrl}`);
  if (isDevelopment) {
    console.log(`🔑 Storage key: ${AUTH_STORAGE_KEY}`);
  }
} else {
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.warn('⚠️  SUPABASE YAPILANDIRILMADI');
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.warn('');
  console.warn('📖 Kurulum rehberi: SUPABASE_ADIM_ADIM_REHBER.md');
  console.warn('🔄 Uygulama mock veri ile çalışacak');
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
}

// Create Supabase client with improved settings
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: isSupabaseConfigured() && isBrowser, // Only persist in browser
    autoRefreshToken: isSupabaseConfigured(),
    detectSessionInUrl: isSupabaseConfigured() && isBrowser, // Only detect in browser
    storage: isBrowser ? window.localStorage : undefined, // Explicit storage
    storageKey: AUTH_STORAGE_KEY, // Explicit key
    flowType: 'pkce', // Use PKCE flow for better security
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Helper function to get current user
export const getCurrentUser = async () => {
  if (!isSupabaseConfigured()) {
    return null;
  }

  const { data: { user }, error } = await supabase.auth.getUser();
  if (error) {
    console.error('Get current user error:', error);
    return null;
  }
  return user;
};

// Helper function to get user profile
export const getUserProfile = async (userId: string) => {
  if (!isSupabaseConfigured()) return null;
  const { data, error } = await supabase.from('profiles').select('*').eq('id', userId).maybeSingle();
  if (error) {
    console.error('Get user profile error:', error);
    return null;
  }
  return data;
};

export const getAuthStorageKey = () => AUTH_STORAGE_KEY;

export const validateStorageData = () => {
  if (!isBrowser || !isSupabaseConfigured()) return false;
  try {
    const raw = window.localStorage.getItem(AUTH_STORAGE_KEY as string);
    if (!raw) return false;
    const parsed = JSON.parse(raw);
    return !!(parsed && (parsed.currentSession || parsed.maybeToken || parsed.user));
  } catch (e) {
    console.warn('validateStorageData error', e);
    return false;
  }
};

// Expose helpful debug helpers to window in development AFTER they are defined
if (isBrowser && isDevelopment) {
  // @ts-ignore
  window.supabase = supabase;
  // @ts-ignore
  window.getAuthStorageKey = getAuthStorageKey;
  // @ts-ignore
  window.validateStorageData = validateStorageData;
  // @ts-ignore
  window.getCurrentUser = getCurrentUser;
  // @ts-ignore
  window.getUserProfile = getUserProfile;

  console.log('🔧 Supabase client exposed to console (DEV only)');
}

export default supabase;
