import { createClient } from '@supabase/supabase-js';
import { Database } from './types';
import { projectId, publicAnonKey } from './info';

// Use credentials from info.tsx (autogenerated by Figma Make)
const supabaseUrl = `https://${projectId}.supabase.co`;
const supabaseAnonKey = publicAnonKey;

// Check if Supabase is properly configured
export const isSupabaseConfigured = (): boolean => {
  return !!(projectId && publicAnonKey && projectId !== 'placeholder');
};

// Check if we're running in browser (client-side)
const isBrowser = typeof window !== 'undefined';

// Storage key for Supabase auth token
const AUTH_STORAGE_KEY = `sb-${projectId}-auth-token`;

// Validate storage key format (ensure projectId is valid)
if (isSupabaseConfigured() && projectId.includes('${')) {
  console.error('❌ Invalid projectId - contains template literal:', projectId);
  console.error('Please check /utils/supabase/info.tsx');
}

// Check if we're in development mode (safe check)
const isDevelopment = typeof import.meta !== 'undefined' && 
                      import.meta.env && 
                      import.meta.env.DEV === true;

// Log configuration status
if (isSupabaseConfigured()) {
  console.log('✅ Supabase bağlantısı başarılı');
  console.log(`📡 Supabase URL: ${supabaseUrl}`);
  if (isDevelopment) {
    console.log(`🔑 Storage key: ${AUTH_STORAGE_KEY}`);
  }
} else {
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.warn('⚠️  SUPABASE YAPILANDIRILMADI');
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.warn('');
  console.warn('📖 Kurulum rehberi: SUPABASE_ADIM_ADIM_REHBER.md');
  console.warn('🔄 Uygulama mock veri ile çalışacak');
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
}

// Create Supabase client with improved settings
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: isSupabaseConfigured() && isBrowser, // Only persist in browser
    autoRefreshToken: isSupabaseConfigured(),
    detectSessionInUrl: isSupabaseConfigured() && isBrowser, // Only detect in browser
    storage: isBrowser ? window.localStorage : undefined, // Explicit storage
    storageKey: AUTH_STORAGE_KEY, // Explicit key
    flowType: 'pkce', // Use PKCE flow for better security
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Export storage key for debugging utilities
export const getAuthStorageKey = () => AUTH_STORAGE_KEY;