import { createClient } from '@supabase/supabase-js';
import { Database } from './types';
import { projectId, publicAnonKey } from './info';

// Use credentials from info.tsx (autogenerated by Figma Make)
const supabaseUrl = `https://${projectId}.supabase.co`;
const supabaseAnonKey = publicAnonKey;

// Check if Supabase is properly configured
export const isSupabaseConfigured = (): boolean => {
  return !!(projectId && publicAnonKey && projectId !== 'placeholder');
};

// Check if we're running in browser (client-side)
const isBrowser = typeof window !== 'undefined';

// Storage key for Supabase auth token
const AUTH_STORAGE_KEY = `sb-${projectId}-auth-token`;

// Validate storage key format (ensure projectId is valid)
if (isSupabaseConfigured() && projectId.includes('${')) {
  console.error('❌ Invalid projectId - contains template literal:', projectId);
  console.error('Please check /utils/supabase/info.tsx');
}

// Check if we're in development mode (safe check)
const isDevelopment = typeof import.meta !== 'undefined' && 
                      import.meta.env && 
                      import.meta.env.DEV === true;

// Log configuration status
if (isSupabaseConfigured()) {
  console.log('✅ Supabase bağlantısı başarılı');
  console.log(`📡 Supabase URL: ${supabaseUrl}`);
  if (isDevelopment) {
    console.log(`🔑 Storage key: ${AUTH_STORAGE_KEY}`);
  }
} else {
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.warn('⚠️  SUPABASE YAPILANDIRILMADI');
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.warn('');
  console.warn('📖 Kurulum rehberi: SUPABASE_ADIM_ADIM_REHBER.md');
  console.warn('🔄 Uygulama mock veri ile çalışacak');
  console.warn('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
}

// Create Supabase client with improved settings
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: isSupabaseConfigured() && isBrowser, // Only persist in browser
    autoRefreshToken: isSupabaseConfigured(),
    detectSessionInUrl: isSupabaseConfigured() && isBrowser, // Only detect in browser
    storage: isBrowser ? window.localStorage : undefined, // Explicit storage
    storageKey: AUTH_STORAGE_KEY, // Explicit key
    flowType: 'pkce', // Use PKCE flow for better security
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Helper function to get current user
export const getCurrentUser = async () => {
  if (!isSupabaseConfigured()) {
    return null;
  }
  
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error) {
    console.error('Get current user error:', error);
    return null;
  }
  return user;
};

// Helper function to get user profile
export const getUserProfile = async (userId: string) => {
  if (!isSupabaseConfigured()) {
    throw new Error('Supabase is not configured');
  }
  
  const { data, error } = await supabase
    .from('users')
    .select('*')
    .eq('id', userId)
    .single();
  
  if (error) throw error;
  return data;
};

// Export storage key for debugging utilities
export const getAuthStorageKey = () => AUTH_STORAGE_KEY;

// Export development mode check for consistency
export const isDevelopmentMode = () => isDevelopment;

// Helper to validate storage data structure (for debugging)
export const validateStorageData = () => {
  if (!isBrowser) return { valid: false, reason: 'Not in browser' };
  
  const storageKey = AUTH_STORAGE_KEY;
  const rawData = localStorage.getItem(storageKey);
  
  if (!rawData) {
    return { valid: false, reason: 'No data found', key: storageKey };
  }
  
  try {
    const parsed = JSON.parse(rawData);
    const hasRequiredFields = !!(
      parsed.access_token &&
      parsed.refresh_token &&
      parsed.user
    );
    
    return {
      valid: hasRequiredFields,
      reason: hasRequiredFields ? 'Valid' : 'Missing required fields',
      key: storageKey,
      data: {
        hasAccessToken: !!parsed.access_token,
        hasRefreshToken: !!parsed.refresh_token,
        hasUser: !!parsed.user,
        expiresAt: parsed.expires_at,
      }
    };
  } catch (error) {
    return { 
      valid: false, 
      reason: 'Invalid JSON', 
      key: storageKey,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
};

// Expose Supabase client and helpers to window (DEVELOPMENT ONLY)
// This allows testing directly from browser console
if (typeof window !== 'undefined') {
  // @ts-ignore
  window.supabase = supabase;
  // @ts-ignore
  window.getAuthStorageKey = getAuthStorageKey;
  // @ts-ignore
  window.validateStorageData = validateStorageData;
  // @ts-ignore
  window.getCurrentUser = getCurrentUser;
  // @ts-ignore
  window.getUserProfile = getUserProfile;
  
  console.log('🔧 Supabase client exposed to console:');
  console.log('  - window.supabase - Supabase client');
  console.log('  - window.getAuthStorageKey() - Get storage key');
  console.log('  - window.validateStorageData() - Validate storage');
  console.log('  - window.getCurrentUser() - Get current user');
  console.log('  - window.getUserProfile(userId) - Get user profile');
}